config/routes.rb
Rails.application.routes.draw do

  resources :directors do
    resources :films
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :films
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :director
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @director = Director.find(params[:id])
    @films = Film.all
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:full_name, :dob)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @director = Director.find(params[:director_id])
  end

  # GET /films/new
  def new
    @film = Film.new
    @director = Director.find(params[:director_id])
  end

  # GET /films/1/edit
  def edit
    @director = Director.find(params[:director_id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)
    @director = Director.find(params[:director_id])
    @film.director = @director
    respond_to do |format|
      if @film.save
        format.html { redirect_to director_path(@director), notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to director_film_path, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :released, :director_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/directors/_form.html.erb
<%= form_with(model: director, local: true) do |form| %>
  <% if director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% director.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing Director</h1>

<%= render 'form', director: @director %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Directors</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directors.each do |director| %>
      <tr>
        <td><%= director.full_name %></td>
        <td><%= director.dob %></td>
        <td><%= link_to 'Show', director %></td>
        <td><%= link_to 'Edit', edit_director_path(director) %></td>
        <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Director', new_director_path %>

app/views/directors/new.html.erb
<h1>New Director</h1>

<%= render 'form', director: @director %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @director.full_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @director.dob %>
</p>

<%= link_to 'New Film', new_director_film_path(@director) %> |
<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>

<table>
  <thead>
    <th>Title</th>
    <th>Release Year</th>
  </thead>
  <tbody>
    <% @films.each do |film| %>
      <% if(film.director.id == @director.id) %>
        <tr>
          <td><%= film.title %></td>
          <td><%= film.released %></td>
          <td><%= link_to 'See more', director_film_path(@director, film) %></td>
          <td><%= link_to 'Edit', edit_director_film_path(@director, film) %></td>
          
          <br>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/films/_form.html.erb
<%= form_with(model: film, url:[@director, film], local: true) do |form| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :released %>
    <%= form.date_field :released %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', director_film_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Released</th>
      <th>Director</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= film.released %></td>
        <td><%= film.director_id %></td>
        <td><%= link_to 'Show', director_film_path(@director, film) %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>


<%= link_to 'Back', @director %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>

<p>
  <strong>Released:</strong>
  <%= @film.released %>
</p>

<p>
  <strong>Director:</strong>
  <%= @film.director_id %>
</p>

<%= link_to 'Edit', edit_director_film_path(@film) %> |
<%= link_to 'Delete', director_film_path(@film), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', director_path(@director) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeNestedResources2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<%= link_to 'Directors', directors_path %>